---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  data_bags_path: /Users/gauravbalyan/Documents/Cloud/chef-repo/cookbooks/awscloudwatch/data_bags/server/ 

platforms:
- name: ubuntu-10.04
  driver:
    box: opscode-ubuntu-10.04
    box_url: /Users/gauravbalyan/Documents/Cloud/opscode_ubuntu-14.04_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[awscloudwatch::default]
    attributes:
